# Site settings
title: Clarkio
header-img: img/home-bg.jpg
email: brian@clarkio.com
description: "Write your site description here. It will be used as your sites meta description as well!"
# baseurl: "/"
url: "http://clarkio.com"
twitter_username: _clarkio
github_username:  clarkio
# facebook_username:

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", "generated_examples"]

gems: [jekyll-paginate]
